baseURL: ""
languageCode: en-us
title: '#show run'
theme: PaperMod
enableEmoji: true
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
  main:
      - name: Home
        url: 'https://showrun.netlify.app'
        weight: 2
      - identifier: archive
        name: Archive
        url: /archives/
        weight: 5
      - identifier: search
        name: Search
        url: /search/
        weight: 10
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 15
      - identifier: categories
        name: Categories
        url: /categories/
        weight: 20
params:
  defaultTheme: auto
  disableThemeToggle: false
  homeInfoParams:
    Title: "Hi!"
    Content: "Welcome to my blog! My name is Luca, I'm a network technician with a few years of experience in a helpdesk team. These articles will try to mix some personal thoughts and the theory behind the technologies I deal with every day at work. I started this blog as a personal project without the presumption that it will become an authoritative source of information. Nevertheless, I will strive to make the articles less chaotic as possible."
  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/luca-tarozzi-9ab371178/'
    - name: github
      url: 'https://github.com/lu-tar/'
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: false

  ShowPostNavLinks: true
