baseURL: ""
languageCode: en-us
title: blog_001
theme: PaperMod
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
  main:
      - name: Home
        url: 'https://628bf6774f42a00056cd100e--moonlit-biscuit-c80413.netlify.app/'
        weight: 2
      - name: Archive
        url: archives
        weight: 5
      - name: Search
        url: search/
        weight: 10
      - name: Tags
        url: tags/
        weight: 15
      - name: Categories
        url: categories/
        weight: 20
params:
  defaultTheme: auto
  disableThemeToggle: false
  homeInfoParams:
    Title: "Hi!"
    Content: "Welcome to my blog"
  socialIcons:
    - name: linkedin
      url: 'https://www.youtube.com/watch?v=G1IbRujko-A'
    - name: github
      url: 'https://www.youtube.com/watch?v=G1IbRujko-A'
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true